### PR TITLE
complete the hello react rails project

### PR DESCRIPTION
**Pull request by jubaer919**
# Highlight 🔍 

   -  Created a new Rails app called 'hello-rails-react'.
        - Use the command rails new -j webpack my_new_rails_app 
    - Verify that the jsbundling-rails gem is added to Gemfile.
    - Initialize my project with Git.
    - Install needed node dependencies as described in the previous lesson's tutorial.
    - Create a babel.config.js in the root folder.
    - Update webpack.config.js to include the babel loader 
    - Make sure that the project has a Postgres database set up.
    - Create a table for storing your messages and create 5 different greetings.
    - Create an API endpoint that selects a random greeting from my table 
    - Create a static view that will be the root of my app.

### CODE REVIEW

**Comment by AmaduKamara** [comment]
Hello @jubaer919, Kindly add a professional README file to your project. 👍🏽

**Review by AmaduKamara — COMMENTED** [review]
## Status: Invalid Submission ❌ ❌ ❌

Hi @jubaer919,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the required Microverse professional README file. 

- [ ] Kindly add a professional README file to document your project 👍🏽
- [ ] To save time on your next submission, kindly include react-router in your project and have a route in your App component t that routes to the Greeting component as required in the project requirement. 👍🏽

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
```

**Review by IngDavidTM — CHANGES_REQUESTED** [review]
## Hi @jubaer919 🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!



## Top highlight 🎯
- The Pull Request follows the GitFlow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [ ] As mentioned by the previous reviewer, ensure the inclusion of `react-router` in your project, and within your App component, create a route leading to the Greeting component as specified in the project requirements :+1:.

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by danmainah — APPROVED** [review]
Hi @jubaer919 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️  Implemented the change requested to add react-router in the App component.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
